[tools]
"github:twpayne/chezmoi" = { version = "2.70.2", platforms = { linux-x64 = { asset_pattern = "chezmoi_{version}_linux-musl_amd64.tar.gz" } } }

[tasks.apply-dotfiles]
run = "chezmoi apply -S ."

[tasks.apply-minimal-dotfiles]
run = """
cp -r minimal/* dot_config/mise/conf.d/
chezmoi apply -S .
rm -r dot_config/mise/conf.d/*
"""

[tasks.bump-mise-tools]
run = "mise upgrade --bump --cd minimal"

[tasks.use-starship]
run = '''
cp assets/starship/tokyo.toml dot_config/starship.toml
'''
